spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payroll_tvm?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Sanjiv
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:h2:mem:payroll_tvm
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
